# Generated by Django 4.2.7 on 2025-09-19 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='is_new',
            field=models.BooleanField(default=False, help_text='Marquer comme nouveau compte'),
        ),
        migrations.AddField(
            model_name='account',
            name='is_promo',
            field=models.BooleanField(default=False, help_text='Marquer comme promotion'),
        ),
        migrations.AddField(
            model_name='account',
            name='promo_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
